# Generated by Django 2.0.2 on 2018-03-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UFoodDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=100)),
                ('ProductID', models.TextField(max_length=200)),
                ('Size', models.TextField(max_length=500)),
                ('Produce', models.TextField(max_length=500)),
            ],
        ),
    ]
