# Generated by Django 2.0.2 on 2018-03-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UFoodDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=100, blank=True)),
                ('Cases', models.CharField(max_length=200, blank=True)),
                ('Hunmiles', models.CharField(max_length=500, blank=True)),
                ('Twohunmiles', models.CharField(max_length=500, blank=True)),
                ('Fivhunmiles', models.CharField(max_length=10, blank=True)),
                ('CsvMonth', models.TextField(max_length=200, blank=True)),
                ('CsvYear', models.TextField(max_length=200, blank=True)),
                ('Local', models.CharField(max_length=10, blank=True)),
            ],
        ),
    ]
